kind: Service
apiVersion: v1
metadata:
  name: warp-speed-frontend-service
  labels:
    app: warp-speed-frontend
spec:
  type: LoadBalancer
  selector:
    app: warp-speed-frontend
  ports:
  - port: 80
    targetPort: 3000
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: warp-speed-frontend-deployment
spec:
  selector:
    matchLabels:
      app: warp-speed-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: warp-speed-frontend
        version: v1
    spec:
      containers:
      - name: warp-speed-frontend
        image: 'eu-frankfurt-1.ocir.io/oraseemeaceeociworkshop/ivandelic/warp/warp-speed-frontend:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ocirsecret
---